<a href="https://colab.research.google.com/github/codeyson/CPE-313/blob/main/Hands_on_Activity_5_1_Text_Similarity_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 5.1 Text Similarity

#### Objective(s):

This activity aims to introduce how to implement text similarity

#### Intended Learning Outcomes (ILOs):
* Demonstrate how to remove special characters from text
* Demonstrate how to measure text simiarity using distance
* Demonstrate how to find text similarity using Count Vector and TF-IDF Vectorizer

#### Resources:
* Jupyter Notebook
* songdata.csv

#### Procedures
Load the necessary libraries

In [68]:
import nltk
import pandas as pd

In [69]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [70]:
data = pd.read_csv('/content/drive/MyDrive/TIP Files/32Sx/CPE 313 (Deep Learning with Python)/Hands-on Activity8.1 | Text Similarity/data/songdata.csv')
data.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nAnd it means something special to me \r\nLook at the way that she smiles when she sees me \r\nHow lucky can one fellow be? \r\n \r\nShe's just my kind of girl, she makes me feel fine \r\nWho could ever believe that she could be mine? \r\nShe's just my kind of girl, without her I'm blue \r\nAnd if she ever leaves me what could I do, what could I do? \r\n \r\nAnd when we go for a walk in the park \r\nAnd she holds me and squeezes my hand \r\nWe'll go on walking for hours and talking \r\nAbout all the things that we plan \r\n \r\nShe's just my kind of girl, she makes me feel fine \r\nWho could ever believe that she could be mine? \r\nShe's just my kind of girl, without her I'm blue \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gently like a summer evening breeze \r\nTake your time, make it slow \r\nAndante, Andante \r\nJust let the feeling grow \r\n \r\nMake your fingers soft and light \r\nLet your body be the velvet of the night \r\nTouch my soul, you know how \r\nAndante, Andante \r\nGo slowly with me now \r\n \r\nI'm your music \r\n(I am your music and I am your song) \r\nI'm your song \r\n(I am your music and I am your song) \r\nPlay me time and time again and make me strong \r\n(Play me again 'cause you're making me strong) \r\nMake me sing, make me sound \r\n(You make me sing and you make me) \r\nAndante, Andante \r\nTread lightly on my ground \r\nAndante, Andante \r\nOh please don't let me down \r\n \r\nThere's a shimmer in your eyes \r\nLike the feeling of a thousand butterflies \r\nPlease don't talk, go on, play \r\nAndante, Andante \r\nAnd let me float away \r\n \r\nI'm your music \r\n(I am your music and I am your song) \r\nI'm your song \r\n(I am your music and I am your song) \r\nPlay me time and time again and make me strong \r\n(Play me again 'cause you're making me strong) \r\nMake me sing, make me sound \r\n(You make me sing and you make me) \r\nAndante, Andante \r\nTread lightly on my ground \r\nAndante, Andante \r\nOh please don't let me down \r\n \r\nMake me sing, make me sound \r\n(You make me sing and you make me) \r\nAndante, Andante \r\nTread lightly on my ground \r\nAndante, Andante \r\nOh please don't let me down \r\nAndante, Andante \r\nOh please don't let me down\r\n\r\n"
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,"I'll never know why I had to go \r\nWhy I had to put up such a lousy rotten show \r\nBoy, I was tough, packing all my stuff \r\nSaying I don't need you anymore, I've had enough \r\nAnd now, look at me standing here again 'cause I found out that \r\nMa ma ma ma ma ma ma ma ma ma ma ma ma ma ma ma my life is here \r\nGotta have you near \r\n \r\nAs good as new, my love for you \r\nAnd keeping it that way is my intention \r\nAs good as new and growing too \r\nYes, I think it's taking on a new dimension \r\nIt's as good as new, my love for you \r\nJust like it used to be and even better \r\nAs good as new, thank God it's true \r\nDarling, we were always meant to stay together \r\n \r\nFeel like a creep, never felt so cheap \r\nNever had a notion that my love could be so deep \r\nHow could I make such a dumb mistake \r\nNow I know I'm not entitled to another break \r\nBut please, baby, I beg you to forgive 'cause I found out that \r\nMa ma ma ma ma ma ma ma ma ma ma ma ma ma ma ma my life is here \r\nGotta get you near \r\n \r\nI thought that our love was at an end but here I am again \r\n \r\nAs good as new, my love for you \r\nAnd keeping it that way is my intention \r\nAs good as new and growing too \r\nYes, I think it's taking on a new dimension \r\nIt's as good as new, my love for you \r\nJust like it used to be and even better \r\nAs good as new, thank God it's true \r\nDarling, we were always meant to stay together \r\n \r\nYes the love I have for you feels as good as new \r\nDarling, we were always meant to stay together\r\n\r\n"
3,ABBA,Bang,/a/abba/bang_20598415.html,"Making somebody happy is a question of give and take \r\nYou can learn how to show it so come on, give yourself a break \r\nEvery smile and every little touch \r\nDon't you know that they mean so much \r\nSweet sweet kisses so tender \r\nAlways will return to sender \r\n \r\nLike a bang, a boom-a-boomerang \r\nDum-be-dum-dum be-dum-be-dum-dum \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nSo give it away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love \r\n \r\nLove is always around and you can look for it anywhere \r\nWhen you feel that you've found it my advice is to take good care \r\nNever use it as a selfish tool \r\nNever ever be such a fool \r\nEvery feeling you're showing \r\nIs a boomerang you're throwing \r\n \r\nYes a bang, a boom-a-boomerang \r\nDum-be-dum-dum be-dum-be-dum-dum \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nSo give it away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\n \r\nAnd if you're warm and tender \r\nI'll kiss you, return to sender \r\nPlease surrender \r\n \r\nBang, a boom-a-boomerang \r\nDum-be-dum-dum be-dum-be-dum-dum \r\nOh bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love\r\n\r\n"
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,"Making somebody happy is a question of give and take \r\nYou can learn how to show it so come on, give yourself a break \r\nEvery smile and every little touch \r\nDon't you know that they mean so much \r\nSweet sweet kisses so tender \r\nAlways will return to sender \r\n \r\nLike a bang, a boom-a-boomerang \r\nDumb-be-dumb-dumb be-dumb-be-dumb-dumb \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nBy giving away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love \r\n \r\nLove is always around and you can look for it anywhere \r\nWhen you feel that you've found it my advice is to take good care \r\nNever use it as a selfish tool \r\nNever ever be such a fool \r\nEvery feeling you're showing \r\nIs a boomerang you're throwing \r\n \r\nYes a bang, a boom-a-boomerang \r\nDumb-be-dumb-dumb be-dumb-be-dumb-dumb \r\nOh bang, a boom-a-boomerang \r\nLove is a tune you hum-de-hum-hum \r\nBy giving away, I think you'll learn \r\nYou'll get love in return \r\nSo bang, a boom-a-boomerang is love \r\n \r\nAnd if you're warm and tender \r\nI'll kiss you, return to sender \r\nPlease surrender \r\n \r\nBang, a boom-a-boomerang \r\nDumb-be-dumb-dumb be-dumb-be-dumb-dumb \r\nOh bang, a boom-a-boomerang is love \r\nA boom-a-boomerang is love\r\n\r\n"

Find the lyrics by the artist The Beatles

In [71]:
beatles = data[data.artist=='The Beatles']
beatles.head()

,artist,song,link,text
1198,The Beatles,A Shot Of Rhythm And Blues,/b/beatles/a+shot+of+rhythm+blues_20014867.html,"Well, if your hands start a-clappin' \r\nAnd your fingers start a-poppin' \r\nAnd your feet start a-movin' around \r\nAnd if you start to swing and sway \r\n \r\nWhen the band starts to play \r\nA real cool way out sound \r\nAnd if you get to can't help it and you can't sit down \r\nYou feel like you gotta move around \r\n \r\nYou get a shot of rhythm and blues. \r\nWith just a little rock and roll on the side \r\nJust for good measure. \r\nGet a pair of dancin' shoes \r\n \r\nWell, with your lover by your side \r\nDon't you know you're gonna have a rockin' time, see'mon! \r\nDon't you worry 'bout a thing \r\nIf you start to dance and sing \r\n \r\nAnd chills come up on you \r\nAnd if the rhythm finally gets you and the beat gets you too \r\nWell, here's something for you to do \r\n \r\nGet a shot of rhythm and blues \r\nWith just a little rock and roll on the side \r\nJust for good measure \r\nGet a pair of dancin' shoes \r\n \r\nWell, with your lover by your side \r\nDon't you know you're gonna have a rockin' time, see'mon! \r\nDon't you worry 'bout a thing \r\nIf you start to dance and sing \r\n \r\nAnd chills come up on you \r\nAnd if the rhythm finally gets you and the beat gets you too \r\nWell, here's something for you to do \r\n \r\nGet a shot of rhythm and blues \r\nGet a pair of dancin' shoes \r\nGet a shot of rhythm and blues \r\nWell, with your lover by your side \r\n \r\nDon't you know you're gonna have a rockin' time, see'mon! \r\nDon't you worry 'bout a thing \r\nIf you start to dance and sing \r\nAnd chills come up on you \r\n \r\nAnd if the rhythm finally gets you and the beat gets you too \r\nWell, here's something for you to do \r\nWell, here's something for you to do \r\nWell, here's something for you to do\r\n\r\n"
1199,The Beatles,Across The Universe,/b/beatles/across+the+universe_10026507.html,"Words are flowing out like \r\nEndless rain into a paper cup \r\nThey slither wildly as they slip away across the universe. \r\nPools of sorrow waves of joy \r\nAre drifting through my opened mind \r\nPossessing and caressing me. \r\n \r\nJai Guru Deva. Om \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\n \r\nImages of broken light, which \r\nDance before me like a million eyes, \r\nThey call me on and on across the universe. \r\nThoughts meander like a \r\nRestless wind inside a letter box \r\nThey tumble blindly as they make their way across the universe. \r\n \r\nJai Guru Deva. Om \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\n \r\nSounds of laughter, shades of life \r\nAre ringing through my opened ears \r\nInciting and inviting me. \r\nLimitless undying love, which \r\nShines around me like a million suns, \r\nIt calls me on and on across the universe \r\n \r\nJai Guru Deva, om. \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\nNothing's gonna change my world \r\n \r\nJai Guru Deva \r\nJai Guru Deva \r\nJai Guru Deva \r\nJai Guru Deva \r\nJai Guru Deva\r\n\r\n"
1200,The Beatles,All I've Got To Do,/b/beatles/all+ive+got+to+do_10026646.html,"Whenever I want you around, yeah \r\nAll I gotta do \r\nIs call you on the phone \r\nAnd you'll come running home, yeah \r\nThat's all I gotta do. \r\n \r\nAnd when I, I wanna kiss you, yeah \r\nAll I gotta do \r\nIs whisper in your ear \r\nThe words you long to hear \r\nAnd I'll be kissing you \r\n \r\nAnd the same goes for me \r\nWhenever you want me at all \r\nI'll be here yes I will \r\nWhenever you call \r\nYou just gotta call on me, yeah \r\nYou just gotta call on me \r\n \r\nAnd when I, I wanna kiss you, yeah \r\nAll I got to do \r\nIs call you on the phone \r\nAnd you'll come running home, yeah \r\nThat's all I gotta do. \r\n \r\nAnd the same goes for me \r\nWhenever you want me at all \r\nI'll be here, yes I will \r\nWhenever you call \r\nYou just gotta call on me \r\nYou just gotta call on me. \r\n \r\nOh, you just gotta call on me\r\n\r\n"
1201,The Beatles,And I Love Her,/b/beatles/and+i+love+her_10026463.html,"I give her all my love \r\nThat's all I do \r\nAnd if you saw my love \r\nYou'd love her to \r\nI love her \r\n \r\nShe gives my everything \r\nAnd tenderly \r\nThe kiss my lover brings \r\nShe brings to me \r\nAnd I love her \r\n \r\nA love like ours \r\nCould never die \r\nAs long as I \r\nHave you near me \r\n \r\nBright are the stars that shine \r\nDark is the sky \r\nI know this love of mine \r\nWill never die \r\nAnd I love her \r\n \r\nBright are the stars that shine \r\nDark is the sky \r\nI know this love of mine \r\nWill never die \r\nAnd I love her, ooh\r\n\r\n"
1202,The Beatles,And Your Bird Can Sing,/b/beatles/and+your+bird+can+sing_10026364.html,"You tell me that you've got everything you want \r\nAnd your bird can sing \r\nBut you don't get me \r\nYou don't get me \r\n \r\nYou say you've seen the seven wonders \r\nAnd you bird is green \r\nBut you can't see me \r\nYou can't see me \r\n \r\nWhen your prized possessions \r\nStart to weigh you down \r\nLook in my direction \r\nI'll be round, I'll be round \r\n \r\nWhen your bird is broken \r\nWill it bring you down \r\nYou may be awoken \r\nI'll be round, I'll be round \r\n \r\nYou tell me that you've heard every sound there is \r\nAnd your bird can swing \r\nBut you can't hear me \r\nYou can't hear me\r\n\r\n"

Check the number of Beatles songs in the data set

In [72]:
data.artist.value_counts().loc[['The Beatles']]

artist
The Beatles    178
Name: count, dtype: int64

Take a look at the first song's lyrics

In [73]:
beatles.iloc[0,3]

"Well, if your hands start a-clappin'  \r\nAnd your fingers start a-poppin'  \r\nAnd your feet start a-movin' around  \r\nAnd if you start to swing and sway  \r\n  \r\nWhen the band starts to play  \r\nA real cool way out sound  \r\nAnd if you get to can't help it and you can't sit down  \r\nYou feel like you gotta move around  \r\n  \r\nYou get a shot of rhythm and blues.  \r\nWith just a little rock and roll on the side  \r\nJust for good measure.  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nWith just a little rock and roll on the side  \r\nJust for good measure  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nGet a pair of dancin' shoes  \r\nGet a shot of rhythm and blues  \r\nWell, with your lover by your side  \r\n  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\nAnd chills come up on you  \r\n  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do\r\n\r\n"

Remove characters from the lyrics

In [74]:
import re

newline = lambda x: re.sub(r'\n', ' ', x) # remove \n
alphanumeric = lambda x: re.sub(r'\w*\d\w*', ' ', x) # remove alphanumeric words

corpus = beatles.text.map(newline).map(alphanumeric)
corpus.head()

1198    Well, if your hands start a-clappin'  \r And your fingers start a-poppin'  \r And your feet start a-movin' around  \r And if you start to swing and sway  \r   \r When the band starts to play  \r A real cool way out sound  \r And if you get to can't help it and you can't sit down  \r You feel like you gotta move around  \r   \r You get a shot of rhythm and blues.  \r With just a little rock and roll on the side  \r Just for good measure.  \r Get a pair of dancin' shoes  \r   \r Well, with your lover by your side  \r Don't you know you're gonna have a rockin' time, see'mon!  \r Don't you worry 'bout a thing  \r If you start to dance and sing  \r   \r And chills come up on you  \r And if the rhythm finally gets you and the beat gets you too  \r Well, here's something for you to do  \r   \r Get a shot of rhythm and blues  \r With just a little rock and roll on the side  \r Just for good measure  \r Get a pair of dancin' shoes  \r   \r Well, with your lover by your side  \r Don't you know you're gonna have a rockin' time, see'mon!  \r Don't you worry 'bout a thing  \r If you start to dance and sing  \r   \r And chills come up on you  \r And if the rhythm finally gets you and the beat gets you too  \r Well, here's something for you to do  \r   \r Get a shot of rhythm and blues  \r Get a pair of dancin' shoes  \r Get a shot of rhythm and blues  \r Well, with your lover by your side  \r   \r Don't you know you're gonna have a rockin' time, see'mon!  \r Don't you worry 'bout a thing  \r If you start to dance and sing  \r And chills come up on you  \r   \r And if the rhythm finally gets you and the beat gets you too  \r Well, here's something for you to do  \r Well, here's something for you to do  \r Well, here's something for you to do\r \r
1199                                                                                                                                                                                                                                                                                                                                                                                                                                         Words are flowing out like  \r Endless rain into a paper cup  \r They slither wildly as they slip away across the universe.  \r Pools of sorrow waves of joy  \r Are drifting through my opened mind  \r Possessing and caressing me.  \r   \r Jai Guru Deva. Om  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r   \r Images of broken light, which  \r Dance before me like a million eyes,  \r They call me on and on across the universe.  \r Thoughts meander like a  \r Restless wind inside a letter box  \r They tumble blindly as they make their way across the universe.  \r   \r Jai Guru Deva. Om  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r   \r Sounds of laughter, shades of life  \r Are ringing through my opened ears  \r Inciting and inviting me.  \r Limitless undying love, which  \r Shines around me like a million suns,  \r It calls me on and on across the universe  \r   \r Jai Guru Deva, om.  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r Nothing's gonna change my world  \r   \r Jai Guru Deva  \r Jai Guru Deva  \r Jai Guru Deva  \r Jai Guru Deva  \r Jai Guru Deva\r \r
1200                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Whenever I want you around, yeah  \r All I gotta do  \r Is call you on the phone  \r And you'll come running home, yeah  \r That's all I gotta do.  \r   \r And when I, I wanna kiss you, yeah  \r All I gotta do  \r Is whisper in your ear  \r The words you long to hear  \r And I'll be kissing you  \r   \r And the same goes for me  \r Whenever you want me at all  \r I'll be here yes I will  \r Whenever you call  \r You just gotta call on me, yeah  \r You just gotta call on me  \r   \r And when I, I wanna kiss you, yeah  \r All I got to do  \r Is call you on the phone  \r And you'll come running home, yeah  \r That's all I gotta do.  \r   \r And the same goes for me  \r Whenever you want me at all  \r I'll be here, yes I will  \r Whenever you call  \r You just gotta call on me  \r You just gotta call on me.  \r   \r Oh, you just gotta call on me\r \r
1201                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      I give her all my love  \r That's all I do  \r And if you saw my love  \r You'd love her to  \r I love her  \r   \r She gives my everything  \r And tenderly  \r The kiss my lover brings  \r She brings to me  \r And I love her  \r   \r A love like ours  \r Could never die  \r As long as I  \r Have you near me  \r   \r Bright are the stars that shine  \r Dark is the sky  \r I know this love of mine  \r Will never die  \r And I love her  \r   \r Bright are the stars that shine  \r Dark is the sky  \r I know this love of mine  \r Will never die  \r And I love her, ooh\r \r
1202                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         You tell me that you've got everything you want  \r And your bird can sing  \r But you don't get me  \r You don't get me  \r   \r You say you've seen the seven wonders  \r And you bird is green  \r But you can't see me  \r You can't see me  \r   \r When your prized possessions  \r Start to weigh you down  \r Look in my direction  \r I'll be round, I'll be round  \r   \r When your bird is broken  \r Will it bring you down  \r You may be awoken  \r I'll be round, I'll be round  \r   \r You tell me that you've heard every sound there is  \r And your bird can swing  \r But you can't hear me  \r You can't hear me\r \r
Name: text, dtype: object

Create a document term matrix using Count Vectorizer with the stop words turned on to English

In [75]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(corpus).toarray()

dt = pd.DataFrame(X, columns=cv.get_feature_names_out()).set_index(beatles.song)
dt.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Across The Universe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
All I've Got To Do,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
And I Love Her,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
And Your Bird Can Sing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Set display options so that the lyrics aren't cut off

In [76]:
pd.set_option('display.max_colwidth', None)

In [77]:
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

Imagine lyrics in Count Vectorizer form

In [78]:
imagine = list(dt.loc['Imagine'])
imagine[:20]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Define the cosine similarity calculation

In [79]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

Calculate all similarities and sort by the most similar

In [80]:
similarity = [cosine(imagine, song) for song in X]
sorted(list(zip(similarity, beatles.song)), reverse=True)[1:6]

[(np.float64(0.22757944185316942), "I'll Cry Instead"),
 (np.float64(0.1738270040532526), 'In My Life'),
 (np.float64(0.16574838603294895), 'Eleanor Rigby'),
 (np.float64(0.1490280831849844), 'In Spite Of All The Danger'),
 (np.float64(0.14592261028699943), 'All My Loving')]

Create the TF-IDF Vectorizer

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Calculate all similarities and sort by the most similar using the TF-IDF data

In [83]:
similarity_tfidf = [cosine(imagine, song) for song in X_tfidf]
sorted(list(zip(similarity_tfidf, beatles.song)), reverse=True)[1:6]

[(np.float64(0.19266277925834221), "I'll Cry Instead"),
 (np.float64(0.18004423848592196), "I'll Get You"),
 (np.float64(0.1551371744116933), 'Eleanor Rigby'),
 (np.float64(0.15054395512050195), 'In My Life'),
 (np.float64(0.12306875209548622), 'Love Of The Loved')]

Compare the lyrics of Imagine and I'll Cry Instead

In [84]:
# Imagine lyrics
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

In [85]:
beatles[beatles.song=='I\'ll Cry Instead'].text

24774    I've got every reason on earth to be mad  \r\n'Cause I just lost the only girl I had  \r\nIf I could get my way  \r\nI'd get myself locked up today  \r\nBut I can't, so I'll cry instead  \r\n  \r\nI've got a chip on my shoulder that's bigger that my feet  \r\nI can't talk to people that I meet  \r\nIf I could see you now  \r\nI'd try to make you sad somehow  \r\nBut I can't, so I'll cry instead  \r\n  \r\nDon't want to cry when there's people there  \r\nI get shy when they start to stare  \r\nI'm gonna hide myself away  \r\nBut I'll come back again someday  \r\n  \r\nAnd when you do you'd better hide all the girls  \r\nI'm gonna break their hearts all round the world  \r\nYes, I'm gonna break them in two  \r\nAnd show you what your lovin' man can do  \r\nUntil then I'll cry instead\r\n\r\n
Name: text, dtype: object

Compare the two lyrics based on the output

# type your answer here
> The two songs have a low similarity score. Some of the words are similar, but most of the words are different, so the lyrics are not very similar.

Find the two Beatles songs that are the most similar
* Using Count Vectorizer
* Using TF-IDF Vectorizer

Calculate the cosine similarity between all combinations of documents

In [86]:

from itertools import combinations

pairs = list(combinations(beatles.song.index, 2)) # all song index combos
pairs_0 = list(combinations(range(len(beatles)), 2)) # all index combos starting with (0,1)
song_pairs = [(beatles.song[a_index], beatles.song[b_index]) for (a_index, b_index) in pairs]
song_pairs[:5]

[('A Shot Of Rhythm And Blues', 'Across The Universe'),
 ('A Shot Of Rhythm And Blues', "All I've Got To Do"),
 ('A Shot Of Rhythm And Blues', 'And I Love Her'),
 ('A Shot Of Rhythm And Blues', 'And Your Bird Can Sing'),
 ('A Shot Of Rhythm And Blues', 'Another Girl')]

 Calculate the cosine similarity of the Count Vectorizer document-term matrix

In [87]:

results = [cosine(X[a_index], X[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8548876342047523), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.8359173188630292),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.8058125835571367), ('And I Love Her', 'Love Me Do')),
 (np.float64(0.7930110315846619), ('If I Fell', 'Love Me Do')),
 (np.float64(0.7478391382739419), ('And I Love Her', 'All You Need Is Love'))]

Calculate the cosine similarity of the TF-IDF Vectorizer document-term matrix

In [88]:

results = [cosine(X_tfidf[a_index], X_tfidf[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8717047783261523),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.6599353568343105), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.6502842517883831), ('Have A Banana!', 'Crinsk Dee Night')),
 (np.float64(0.6232797327325461), ("Don't Let Me Down", 'Let It Be')),
 (np.float64(0.5275364336322863), ('If I Fell', 'Love Me Do'))]

In [89]:

beatles[beatles.song=='All You Need Is Love'].text

24695    Love, love, love, love, love, love, love, love, love.  \r\n  \r\nThere's nothing you can do that can't be done.  \r\nNothing you can sing that can't be sung.  \r\nNothing you can say, but you can learn  \r\nHow to play the game  \r\nIt's easy.  \r\nNothing you can make that can't be made.  \r\nNo one you can save that can't be saved.  \r\nNothing you can do, but you can learn  \r\nHow to be you in time  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nLove, love, love, love, love, love, love, love, love.  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\n  \r\nThere's nothing you can know that isn't known.  \r\nNothing you can see that isn't shown.  \r\nThere's nowhere you can be that isn't where  \r\nYou're meant to be  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nAll you need is love. (All together now).  \r\nAll you need is love. (Everybody).  \r\nAll you need is love, love. Love is all you need.  \r\nLove is all you need.  \r\nLove is all you need  \r\n  \r\n(Yesterday)  \r\n(Oh yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(Oh, yesterday)\r\n\r\n
Name: text, dtype: object

In [90]:
beatles[beatles.song=='Love Me Do'].text

24805    Love, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nSomeone to love,  \r\nSomebody new.  \r\nSomeone to love,  \r\nSomeone like you.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\nYeah, love me do.  \r\nWhoa, oh, love me do.\r\n\r\n
Name: text, dtype: object

In [91]:
beatles[beatles.song=='If I Needed Someone'].text

24768    If I needed someone to love  \r\nYou're the one that I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah, ah, ah  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah\r\n\r\n
Name: text, dtype: object

In [92]:
beatles[beatles.song=='If I Needed Someone To Love'].text

24769    If I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nIf I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone\r\n\r\n
Name: text, dtype: object

In [93]:
beatles[beatles.song=='Have A Banana!'].text

1221    [Speech]  \r\n  \r\nBrian Matthew: Is that it? Is that the end?  \r\nPaul: Yeah, yeah, that's it.  \r\nJohn: Fade, fade!  \r\nBrian: Good track. Oh, well, we'll stop there, stop there, stop there.  \r\nJohn: What an end!  \r\nBrian: Quiet! All right, George.  \r\nJohn: Fade!  \r\nBrian: Hold it!  \r\nGeorge: Oh, thank you.  \r\nJohn: Fade, you silly.  \r\nBrian: Well, we did. We did that. Oh, no! No! We've done that bit!  \r\nJohn: The train comes in now.  \r\nBrian: We did that.  \r\nJohn: Yeah.  \r\nBrian: To pove we weren't playing the record, then, you see. 'Cause,\r\notherwise, there's no point in you being here, is there? Ha, ha, ha!  \r\nJohn: Yeah, we did that, 'cause it sounds just like it, don't it?  \r\nBrian: Pretty cool lot of fellows, aren't you? Here, Ringo, have a banana,\r\ncatch!\r\n\r\n
Name: text, dtype: object

In [94]:
beatles[beatles.song=='Crinsk Dee Night'].text

24713    [Speech]  \r\n  \r\nBrian Matthew: The next few minutes, we're in the lap of the gods and the\r\nhands of the Beatles. In my young days, when I was a lad, they used to have\r\nactors in films and now that they--  \r\nPaul: Yes?  \r\nJohn: Hey! Listen!  \r\nPaul: It's all changed, now, Brian. They're not doing that, no actors.  \r\nJohn: It's all changed, now.  \r\nBrian: But this is what I wonder. In those days, the actors used to say their\r\nbest bits were left on the cutting room floor. Did you find that?  \r\nJohn: No, no, no, those were the good bits in the film. You should have seen\r\nthe rest.  \r\nBrian: Yes?  \r\nJohn: Rubbish!  \r\nBrian: Was it, really?  \r\nJohn: Even worse, yes.  \r\nBrian: Who was worst?  \r\nJohn: Oh, Paul.  \r\nBrian: I see.  \r\nPaul: I think John was about the worst.  \r\nJohn: No, it was you.  \r\nPaul: Oh, Ringo was very good. He was. He's a good lad.  \r\nBrian: He was. They're saying he's a new Charlie Chaplin. Do you think that's\r\nright?  \r\nJohn: He was miming.  \r\nPaul: You, too, with Jason.  \r\nJohn: Oh, yes, he's an old one. Okay, Ring?  \r\nBrian: Beginning to look like that. Now, then--  \r\nRingo: All right, John. Can you hear me?  \r\nPaul: Can you hear him? Hello!  \r\nBrian: Not really. I hope not. I hope not!  \r\nJohn: We brought you the flowers, Ring.  \r\nBrian: He's not allowed to talk.  \r\nRingo: Eh?  \r\nJohn: We brought you the flowers.  \r\nRingo: Oh, good.  \r\nJohn: And the grapes.  \r\nRingo: Oh, I like grapes.  \r\nPaul: He likes grapes.  \r\nGeorge: We've been to Portugal.  \r\nBrian: Guess who's, guess who's top of the pops in Portugal, then.  \r\nAll: Who?  \r\nBrian: Los Beatles.  \r\nJohn: Los Beatles? Great, great laugh.  \r\nBrian: I don't suppose you know the title of your film in Portuguese?  \r\nJohn: No. Crinsk dee Night?  \r\nBrian: Could be. Let's hear the number, shall we?  \r\nJohn: Right\r\n\r\n
Name: text, dtype: object

Compare the results. Which Vectorizer seems to do a better job?

#type your answer here
> The TF-IDF vectorixzer provides better result. By comparing the two, the first one got a similarity scoer of around 0.19, however the second one was around 0.60. It's obviously better.

#### Supplementary Activity

* Use a dataset that consists of text document
* Remove special characters
* Compare the similar document using Count Vector and TF-IDF Vectorizer
* Use the cosine similarity to measure the similarity of text

In [95]:
# Use a dataset that consists of text document
supp = pd.read_excel('/content/drive/MyDrive/TIP Files/32Sx/CPE 313 (Deep Learning with Python)/Hands-on Activity8.1 | Text Similarity/data/warnews.xlsx')
supp.head()

,Headlines,Summary,Press,Date,Keyword
0,I served in Iraq and Afghanistan but the horrors of war turned me into an \n£120 an hour sex worker...,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan
1,The forever war in Afghanistan is nowhere near its end. Now IS indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan
2,"Hell at Abbey Gate: Chaos, Confusion and Death in the Final Days of the War \nin Afghanistan","In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan
3,‘A second Afghanistan’: Doubts over Russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan
4,Afghanistan: Former army general vows new war against Taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan

## Demonstrate how to remove special characters from text

### Tokenize (words)

In [96]:
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

supp['word_tokens'] = supp.Headlines.map(word_tokenize)
supp.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,Headlines,Summary,Press,Date,Keyword,word_tokens
0,I served in Iraq and Afghanistan but the horrors of war turned me into an \n£120 an hour sex worker...,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]"
1,The forever war in Afghanistan is nowhere near its end. Now IS indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]"
2,"Hell at Abbey Gate: Chaos, Confusion and Death in the Final Days of the War \nin Afghanistan","In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]"
3,‘A second Afghanistan’: Doubts over Russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]"
4,Afghanistan: Former army general vows new war against Taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]"

### Tokenize (words with remove punctuation) / Tokenize (words with remove special characters and numbers)

In [97]:
# Remove special characters
import re
remove_special = lambda x: re.sub(r'[!?£]' ,' ', x.lower())
supp['special'] = supp.Headlines.map(remove_special).map(word_tokenize)


supp.head()

,Headlines,Summary,Press,Date,Keyword,word_tokens,special
0,I served in Iraq and Afghanistan but the horrors of war turned me into an \n£120 an hour sex worker...,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]"
1,The forever war in Afghanistan is nowhere near its end. Now IS indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]"
2,"Hell at Abbey Gate: Chaos, Confusion and Death in the Final Days of the War \nin Afghanistan","In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]"
3,‘A second Afghanistan’: Doubts over Russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]"
4,Afghanistan: Former army general vows new war against Taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]"

In [98]:
# remove numbers
remove_number = lambda x: re.sub(r'[/d!?]' ,' ', x.lower())
supp['remove_num'] = supp.Headlines.map(remove_number).map(word_tokenize)

supp.head()

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num
0,I served in Iraq and Afghanistan but the horrors of war turned me into an \n£120 an hour sex worker...,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]","[i, serve, in, iraq, an, afghanistan, but, the, horrors, of, war, turne, me, into, an, £120, an, hour, sex, worker, ...]"
1,The forever war in Afghanistan is nowhere near its end. Now IS indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, en, ., now, is, in, ulging, in, ethnic, warfare]"
2,"Hell at Abbey Gate: Chaos, Confusion and Death in the Final Days of the War \nin Afghanistan","In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, an, eath, in, the, final, ays, of, the, war, in, afghanistan]"
3,‘A second Afghanistan’: Doubts over Russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]"
4,Afghanistan: Former army general vows new war against Taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]"

### Tokenize (words with remove punctuation and all lowercase)

In [99]:
# This regular expression removes all punctuation
import string

punc_re = lambda x: re.sub('[%s]' % re.escape(string.punctuation), ' ', x)
supp['Headlines'] = supp.Headlines.map(punc_re)

supp.head()

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num
0,I served in Iraq and Afghanistan but the horrors of war turned me into an \n£120 an hour sex worker,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]","[i, serve, in, iraq, an, afghanistan, but, the, horrors, of, war, turne, me, into, an, £120, an, hour, sex, worker, ...]"
1,The forever war in Afghanistan is nowhere near its end Now IS indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, en, ., now, is, in, ulging, in, ethnic, warfare]"
2,Hell at Abbey Gate Chaos Confusion and Death in the Final Days of the War \nin Afghanistan,"In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, an, eath, in, the, final, ays, of, the, war, in, afghanistan]"
3,‘A second Afghanistan’ Doubts over Russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]"
4,Afghanistan Former army general vows new war against Taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]"

In [100]:
# This regular expression removes all words with numbers in them and also makes all words lowercase
import re

lower_alpha = lambda x: re.sub(r"""\w*\d\w*""", ' ', x.lower())
supp['Headlines'] = supp.Headlines.map(lower_alpha)

supp.head()

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num
0,i served in iraq and afghanistan but the horrors of war turned me into an \n£ an hour sex worker,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]","[i, serve, in, iraq, an, afghanistan, but, the, horrors, of, war, turne, me, into, an, £120, an, hour, sex, worker, ...]"
1,the forever war in afghanistan is nowhere near its end now is indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, en, ., now, is, in, ulging, in, ethnic, warfare]"
2,hell at abbey gate chaos confusion and death in the final days of the war \nin afghanistan,"In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, an, eath, in, the, final, ays, of, the, war, in, afghanistan]"
3,‘a second afghanistan’ doubts over russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]"
4,afghanistan former army general vows new war against taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]"

### Tokenize (words with remove punctuation, all lowercase and remove stop words)

In [101]:
nltk.download('stopwords')
# Remove stop words
from nltk.corpus import stopwords

stop_words = stopwords.words('english')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [102]:
stop_lambda = lambda x: [y for y in x if y not in stop_words]
supp['tokens_stop'] = supp.remove_num.apply(stop_lambda)
supp.head()

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num,tokens_stop
0,i served in iraq and afghanistan but the horrors of war turned me into an \n£ an hour sex worker,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]","[i, serve, in, iraq, an, afghanistan, but, the, horrors, of, war, turne, me, into, an, £120, an, hour, sex, worker, ...]","[serve, iraq, afghanistan, horrors, war, turne, £120, hour, sex, worker, ...]"
1,the forever war in afghanistan is nowhere near its end now is indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, en, ., now, is, in, ulging, in, ethnic, warfare]","[forever, war, afghanistan, nowhere, near, en, ., ulging, ethnic, warfare]"
2,hell at abbey gate chaos confusion and death in the final days of the war \nin afghanistan,"In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, an, eath, in, the, final, ays, of, the, war, in, afghanistan]","[hell, abbey, gate, :, chaos, ,, confusion, eath, final, ays, war, afghanistan]"
3,‘a second afghanistan’ doubts over russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]","[‘, secon, afghanistan, ’, :, oubts, russia, ’, war, prosecution]"
4,afghanistan former army general vows new war against taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, taliban]"

### Tokenize (words with remove punctuation, all lowercase and  remove stop words, with speech_tagging)

In [103]:
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
# Parts of speech tagging
from nltk.tag import pos_tag

pos_lambda = lambda x: nltk.pos_tag(x)
supp['tokens_pos'] = (supp.tokens_stop.apply(pos_lambda))
supp.head()

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num,tokens_stop,tokens_pos
0,i served in iraq and afghanistan but the horrors of war turned me into an \n£ an hour sex worker,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[I, served, in, Iraq, and, Afghanistan, but, the, horrors, of, war, turned, me, into, an, £120, an, hour, sex, worker, ...]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]","[i, serve, in, iraq, an, afghanistan, but, the, horrors, of, war, turne, me, into, an, £120, an, hour, sex, worker, ...]","[serve, iraq, afghanistan, horrors, war, turne, £120, hour, sex, worker, ...]","[(serve, NN), (iraq, NN), (afghanistan, JJ), (horrors, NNS), (war, NN), (turne, JJ), (£120, NNP), (hour, NN), (sex, NN), (worker, NN), (..., :)]"
1,the forever war in afghanistan is nowhere near its end now is indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[The, forever, war, in, Afghanistan, is, nowhere, near, its, end, ., Now, IS, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, en, ., now, is, in, ulging, in, ethnic, warfare]","[forever, war, afghanistan, nowhere, near, en, ., ulging, ethnic, warfare]","[(forever, RB), (war, NN), (afghanistan, NN), (nowhere, RB), (near, IN), (en, NN), (., .), (ulging, VBG), (ethnic, JJ), (warfare, NN)]"
2,hell at abbey gate chaos confusion and death in the final days of the war \nin afghanistan,"In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[Hell, at, Abbey, Gate, :, Chaos, ,, Confusion, and, Death, in, the, Final, Days, of, the, War, in, Afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, an, eath, in, the, final, ays, of, the, war, in, afghanistan]","[hell, abbey, gate, :, chaos, ,, confusion, eath, final, ays, war, afghanistan]","[(hell, NN), (abbey, JJ), (gate, NN), (:, :), (chaos, NN), (,, ,), (confusion, NN), (eath, FW), (final, JJ), (ays, NNS), (war, NN), (afghanistan, NN)]"
3,‘a second afghanistan’ doubts over russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]","[‘, secon, afghanistan, ’, :, oubts, russia, ’, war, prosecution]","[(‘, JJ), (secon, NN), (afghanistan, JJ), (’, NN), (:, :), (oubts, JJ), (russia, NN), (’, NNP), (war, NN), (prosecution, NN)]"
4,afghanistan former army general vows new war against taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[Afghanistan, :, Former, army, general, vows, new, war, against, Taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, taliban]","[(afghanistan, NN), (:, :), (former, JJ), (army, NN), (general, NN), (vows, VBZ), (new, JJ), (war, NN), (taliban, NN)]"

## Demonstrate how to measure text similarity using distance

In [104]:
press = supp[supp.Press=='Al Jazeera']
press.head()

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num,tokens_stop,tokens_pos
3,‘a second afghanistan’ doubts over russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, A, second, Afghanistan, ’, :, Doubts, over, Russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]","[‘, secon, afghanistan, ’, :, oubts, russia, ’, war, prosecution]","[(‘, JJ), (secon, NN), (afghanistan, JJ), (’, NN), (:, :), (oubts, JJ), (russia, NN), (’, NNP), (war, NN), (prosecution, NN)]"
71,‘flashback’ ukraine war revives painful memories for afghans,Other Afghans look at the war and see parallels with their own more ... a \nwoman from Afghanistan who works with refugees at a counselling...,Al Jazeera,1 month ago,Afghanistan,"[‘, Flashback, ’, :, Ukraine, war, revives, painful, memories, for, Afghans]","[‘, flashback, ’, :, ukraine, war, revives, painful, memories, for, afghans]","[‘, flashback, ’, :, ukraine, war, revives, painful, memories, for, afghans]","[‘, flashback, ’, :, ukraine, war, revives, painful, memories, afghans]","[(‘, JJ), (flashback, NN), (’, NN), (:, :), (ukraine, JJ), (war, NN), (revives, NNS), (painful, JJ), (memories, NNS), (afghans, NNS)]"
82,biden defends afghanistan pullout amid airport chaos,"The Taliban has declared the war in Afghanistan over, after its fighters \nswept into the capital, Kabul, and President Ashraf Ghani fled the...",Al Jazeera,2021-08-16 00:00:00,Afghanistan,"[Biden, defends, Afghanistan, pullout, amid, airport, chaos]","[biden, defends, afghanistan, pullout, amid, airport, chaos]","[bi, en, efen, s, afghanistan, pullout, ami, airport, chaos]","[bi, en, efen, afghanistan, pullout, ami, airport, chaos]","[(bi, NN), (en, FW), (efen, FW), (afghanistan, FW), (pullout, NN), (ami, NN), (airport, NN), (chaos, NN)]"
109,timeline how september led to us’s longest war,"The 20-year conflict left about 69,000 Afghan security forces and at ... to \nend the two wars in Iraq and Afghanistan – there is a surge in...",Al Jazeera,2021-09-06 00:00:00,Afghanistan,"[Timeline, :, How, September, 11, ,, 2001, led, to, US, ’, s, longest, war]","[timeline, :, how, september, 11, ,, 2001, led, to, us, ’, s, longest, war]","[timeline, :, how, september, 11, ,, 2001, le, to, us, ’, s, longest, war]","[timeline, :, september, 11, ,, 2001, le, us, ’, longest, war]","[(timeline, NN), (:, :), (september, NN), (11, CD), (,, ,), (2001, CD), (le, NN), (us, PRP), (’, VBP), (longest, JJS), (war, NN)]"
121,aid cut off may kill more afghans than war,Aid cut-off may kill more Afghans than war. Urgent action is needed by the \ninternational community to prevent catastrophic hunger in Afghanistan...,Al Jazeera,2021-12-04 00:00:00,Afghanistan,"[Aid, cut-off, may, kill, more, Afghans, than, war]","[aid, cut-off, may, kill, more, afghans, than, war]","[ai, cut-off, may, kill, more, afghans, than, war]","[ai, cut-off, may, kill, afghans, war]","[(ai, JJ), (cut-off, NN), (may, MD), (kill, VB), (afghans, NNS), (war, NN)]"

In [105]:
import re

newline = lambda x: re.sub(r'\n', ' ', x) # remove \n
alphanumeric = lambda x: re.sub(r'\w*\d\w*', ' ', x) # remove alphanumeric words

corpus_supp = press.Headlines.map(newline).map(alphanumeric)
corpus_supp.head()

3       ‘a second afghanistan’  doubts over russia’s war prosecution
71     ‘flashback’  ukraine war revives painful memories for afghans
82              biden defends afghanistan pullout amid airport chaos
109             timeline  how september      led to us’s longest war
121                       aid cut off may kill more afghans than war
Name: Headlines, dtype: object

In [106]:
from sklearn.feature_extraction.text import CountVectorizer

cv_supp = CountVectorizer(stop_words="english")
X_supp = cv_supp.fit_transform(corpus_supp).toarray()

dt_supp = pd.DataFrame(X_supp, columns=cv_supp.get_feature_names_out()).set_index(corpus_supp)
dt_supp.head()

,abating,abdelaziz,abraham,absolutely,abuses,academics,accidental,accords,accountable,accuse,...,worth,wound,wounded,wrong,xi,year,years,yemen,zelenskyy,zemmour
Headlines,,,,,,,,,,,,,,,,,,,,,
‘a second afghanistan’ doubts over russia’s war prosecution,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
‘flashback’ ukraine war revives painful memories for afghans,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
biden defends afghanistan pullout amid airport chaos,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
timeline how september led to us’s longest war,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aid cut off may kill more afghans than war,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [107]:
selected_headline = corpus_supp.iloc[0]
press_headline_vector = list(dt_supp.loc[selected_headline])
press_headline_vector[:20]

['abating',
 'abdelaziz',
 'abraham',
 'absolutely',
 'abuses',
 'academics',
 'accidental',
 'accords',
 'accountable',
 'accuse',
 'accuses',
 'accusing',
 'act',
 'activists',
 'admits',
 'advancing',
 'adversity',
 'advisory',
 'affair',
 'affected']

In [108]:
from itertools import combinations

pairs_0 = list(combinations(range(len(corpus_supp)), 2)) # all index combos for corpus_supp

supp_headline_pairs = [(corpus_supp.iloc[a_index], corpus_supp.iloc[b_index]) for (a_index, b_index) in pairs_0]
supp_headline_pairs[:5]

[('‘a second afghanistan’  doubts over russia’s war prosecution',
  '‘flashback’  ukraine war revives painful memories for afghans'),
 ('‘a second afghanistan’  doubts over russia’s war prosecution',
  'biden defends afghanistan pullout amid airport chaos'),
 ('‘a second afghanistan’  doubts over russia’s war prosecution',
  'timeline  how september      led to us’s longest war'),
 ('‘a second afghanistan’  doubts over russia’s war prosecution',
  'aid cut off may kill more afghans than war'),
 ('‘a second afghanistan’  doubts over russia’s war prosecution',
  'taliban claims victory in panjshir as it calls to end war')]

In [109]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

In [110]:
results = [cosine(X_supp[a_index], X_supp[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, supp_headline_pairs), reverse=True)[:5]

[(np.float64(1.0000000000000002),
  ('‘a second afghanistan’  doubts over russia’s war prosecution',
   '‘a second afghanistan’  doubts over russia’s war prosecution')),
 (np.float64(1.0000000000000002),
  ('why is the us unequivocal in its support for israel ',
   'why is the us unequivocal in its support for israel ')),
 (np.float64(1.0000000000000002),
  ('timeline  week seven of russia’s war in ukraine',
   'timeline  week seven of russia’s war in ukraine')),
 (np.float64(1.0000000000000002),
  ('the russia ukraine war provides an opportunity to reform the un',
   'the russia ukraine war provides an opportunity to reform the un')),
 (np.float64(1.0000000000000002),
  ('president zelenskyy  one israel is enough',
   'president zelenskyy  one israel is enough'))]

## Demonstrate how to find text similarity using Count Vector and TF-IDF Vectorizer

In [111]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize

supp['word_tokens'] = supp.Headlines.map(word_tokenize)

supp.head()

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,Headlines,Summary,Press,Date,Keyword,word_tokens,special,remove_num,tokens_stop,tokens_pos
0,i served in iraq and afghanistan but the horrors of war turned me into an \n£ an hour sex worker,"A WAR hero traumatised by the horrors of combat is now working as a \n£120-an-hour escort.Grace Parker, 35, served in Iraq and Afghanistan but...",The Sun,1 day ago,Afghanistan,"[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, £, an, hour, sex, worker]","[i, served, in, iraq, and, afghanistan, but, the, horrors, of, war, turned, me, into, an, 120, an, hour, sex, worker, ...]","[i, serve, in, iraq, an, afghanistan, but, the, horrors, of, war, turne, me, into, an, £120, an, hour, sex, worker, ...]","[serve, iraq, afghanistan, horrors, war, turne, £120, hour, sex, worker, ...]","[(serve, NN), (iraq, NN), (afghanistan, JJ), (horrors, NNS), (war, NN), (turne, JJ), (£120, NNP), (hour, NN), (sex, NN), (worker, NN), (..., :)]"
1,the forever war in afghanistan is nowhere near its end now is indulging in \nethnic warfare,"Islamic State is seeking to overthrow the Taliban—quietly helped along by \nthe discontent in its own ranks, economic crisis, and disputes...",ThePrint,2 weeks ago,Afghanistan,"[the, forever, war, in, afghanistan, is, nowhere, near, its, end, now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, end, ., now, is, indulging, in, ethnic, warfare]","[the, forever, war, in, afghanistan, is, nowhere, near, its, en, ., now, is, in, ulging, in, ethnic, warfare]","[forever, war, afghanistan, nowhere, near, en, ., ulging, ethnic, warfare]","[(forever, RB), (war, NN), (afghanistan, NN), (nowhere, RB), (near, IN), (en, NN), (., .), (ulging, VBG), (ethnic, JJ), (warfare, NN)]"
2,hell at abbey gate chaos confusion and death in the final days of the war \nin afghanistan,"In firsthand accounts, Afghan civilians and U.S. Marines describe the \ndesperate struggle to flee through the Kabul airport's last open...",ProPublica,1 month ago,Afghanistan,"[hell, at, abbey, gate, chaos, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, and, death, in, the, final, days, of, the, war, in, afghanistan]","[hell, at, abbey, gate, :, chaos, ,, confusion, an, eath, in, the, final, ays, of, the, war, in, afghanistan]","[hell, abbey, gate, :, chaos, ,, confusion, eath, final, ays, war, afghanistan]","[(hell, NN), (abbey, JJ), (gate, NN), (:, :), (chaos, NN), (,, ,), (confusion, NN), (eath, FW), (final, JJ), (ays, NNS), (war, NN), (afghanistan, NN)]"
3,‘a second afghanistan’ doubts over russia’s war prosecution,Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.,Al Jazeera,5 days ago,Afghanistan,"[‘, a, second, afghanistan, ’, doubts, over, russia, ’, s, war, prosecution]","[‘, a, second, afghanistan, ’, :, doubts, over, russia, ’, s, war, prosecution]","[‘, a, secon, afghanistan, ’, :, oubts, over, russia, ’, s, war, prosecution]","[‘, secon, afghanistan, ’, :, oubts, russia, ’, war, prosecution]","[(‘, JJ), (secon, NN), (afghanistan, JJ), (’, NN), (:, :), (oubts, JJ), (russia, NN), (’, NNP), (war, NN), (prosecution, NN)]"
4,afghanistan former army general vows new war against taliban,Lt Gen Sami Sadat tells the BBC of planned operations but many Afghans are \nweary of more conflict.,BBC,1 week ago,Afghanistan,"[afghanistan, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, against, taliban]","[afghanistan, :, former, army, general, vows, new, war, taliban]","[(afghanistan, NN), (:, :), (former, JJ), (army, NN), (general, NN), (vows, VBZ), (new, JJ), (war, NN), (taliban, NN)]"

In [112]:
from sklearn.feature_extraction.text import CountVectorizer

cv_supp = CountVectorizer(stop_words="english")
X_supp = cv_supp.fit_transform(corpus_supp).toarray()

dt_supp = pd.DataFrame(X_supp, columns=cv_supp.get_feature_names_out()).set_index(corpus_supp)
dt_supp.head()

,abating,abdelaziz,abraham,absolutely,abuses,academics,accidental,accords,accountable,accuse,...,worth,wound,wounded,wrong,xi,year,years,yemen,zelenskyy,zemmour
Headlines,,,,,,,,,,,,,,,,,,,,,
‘a second afghanistan’ doubts over russia’s war prosecution,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
‘flashback’ ukraine war revives painful memories for afghans,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
biden defends afghanistan pullout amid airport chaos,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
timeline how september led to us’s longest war,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
aid cut off may kill more afghans than war,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [113]:
pd.set_option('display.max_colwidth', None)

In [114]:
press[press.Press=='Al Jazeera'].Summary

3                                         Russia's lack of progress in its war against Ukraine has been noted by \nanalysts since it launched a second phase.
71             Other Afghans look at the war and see parallels with their own more ... a \nwoman from Afghanistan who works with refugees at a counselling...
82           The Taliban has declared the war in Afghanistan over, after its fighters \nswept into the capital, Kabul, and President Ashraf Ghani fled the...
109           The 20-year conflict left about 69,000 Afghan security forces and at ... to \nend the two wars in Iraq and Afghanistan – there is a surge in...
121     Aid cut-off may kill more Afghans than war. Urgent action is needed by the \ninternational community to prevent catastrophic hunger in Afghanistan...
                                                                                ...
5605        “The Yemen conflict has just hit another shameful milestone: 10,000 \nchildren have been killed or maimed since fighting started in March 2015...
5616         Has a dangerous new phase of the war in Yemen begun? Houthi rebels have \nlaunched attacks on the United Arab Emirates for the second time in...
5617     Yemen: Survivors slam Saudi coalition attack on detention centre. Survivors \nof detention centre air raids denounce the attack in Saada province...
5620        Yemen's grinding conflict has killed tens of thousands and displaced \nmillions, resulting in what the UN calls the world's worst humanitarian...
5624        The war in Yemen has pitted the Houthis against various opponents, \nincluding the Yemeni government, which is backed by a Saudi-led coalition...
Name: Summary, Length: 445, dtype: object

In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf_supp = TfidfVectorizer(stop_words="english")
X_tfidf_supp = cv_tfidf_supp.fit_transform(corpus_supp).toarray()

dt_tfidf_supp = pd.DataFrame(X_tfidf_supp, columns=cv_tfidf_supp.get_feature_names_out()).set_index(corpus_supp)
dt_tfidf_supp.head()

,abating,abdelaziz,abraham,absolutely,abuses,academics,accidental,accords,accountable,accuse,...,worth,wound,wounded,wrong,xi,year,years,yemen,zelenskyy,zemmour
Headlines,,,,,,,,,,,,,,,,,,,,,
‘a second afghanistan’ doubts over russia’s war prosecution,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
‘flashback’ ukraine war revives painful memories for afghans,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
biden defends afghanistan pullout amid airport chaos,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
timeline how september led to us’s longest war,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
aid cut off may kill more afghans than war,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [116]:
selected_headline = corpus_supp.iloc[0]
selected_headline_tfidf_vector = X_tfidf_supp[0]

similarity_tfidf = [cosine(selected_headline_tfidf_vector, vec)for vec in X_tfidf_supp]

sorted_similarities_tfidf = sorted(list(zip(similarity_tfidf, corpus_supp)),reverse=True)

sorted_similarities_tfidf[1:6]

[(np.float64(1.0),
  '‘a second afghanistan’  doubts over russia’s war prosecution'),
 (np.float64(0.2178150516895805),
  'that time the vietnam war led to the war in afghanistan'),
 (np.float64(0.1946263723944857),
  'afghanistan  visualising the impact of   years of war'),
 (np.float64(0.18496427710902216),
  'israeli fighter jets attack gaza for second time in a week'),
 (np.float64(0.17456281922907663),
  'pakistan’s imran khan warns of ‘civil war’ in afghanistan')]

In [117]:
selected_headline_cv_vector = X_supp[0]
similarity_supp_cv = [cosine(selected_headline_cv_vector, headline_vec) for headline_vec in X_supp]
sorted_similarities_cv = sorted(list(zip(similarity_supp_cv, corpus_supp)), reverse=True)
sorted_similarities_cv[1:6]

[(np.float64(1.0000000000000002),
  '‘a second afghanistan’  doubts over russia’s war prosecution'),
 (np.float64(0.43301270189221935),
  'that time the vietnam war led to the war in afghanistan'),
 (np.float64(0.3651483716701107),
  'timeline  week eight of russia’s war in ukraine'),
 (np.float64(0.3651483716701107),
  'afghanistan  visualising the impact of   years of war'),
 (np.float64(0.33333333333333337),
  'timeline  week seven of russia’s war in ukraine')]

#### Conclusion

#type your answer here
> This activity helps me learn how to measure text similarity using distance, CountVector, and TF-IDF. While I am doing the steps, I realize that the text cannot be compared directly, so it needs to change into numbers first before the computer can compare them. I also notice that cosine similarity gives a number to show how similar two texts are. When the result is 1, I think it is wrong at first, but then I understand that it means the texts are the same. There are many steps and new terms, so I feel confused sometimes while doing the activity, but while I continue working, I slowly understand how the process works.